[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  name = "github.com/crewjam/saml"
  version = "0.3.1"

[[constraint]]
  name = "github.com/dustin/go-humanize"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "1.1.1"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/skip2/go-qrcode"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/gomail.v2"
  branch = "v2"

[prune]
  go-tests = true
  unused-packages = true
